### ISSUE TITLE
运行dev:h5白屏

### ISSUE THREAD

**Issue by zjhr** [mistjs/taro-vue3-starter#1]
把模板clone下来后，yarn安装完成，然后运行dev:h5就报【Cannot read properties of undefined (reading 'replace')】，页面打开是白屏，dev:weapp倒没问题。
![screenshot-20220728-194626](https://user-images.githubusercontent.com/16950097/181497550-f6199b2f-d7a0-4a94-a98b-044bf4d58274.png)

**Comment by aibayanyu20** [comment]
测试过了，是unplugin-components不生效导致的，改了一下支持了，但是unocss的兼容有问题，后面等升级pnpm再正式支持h5
